### ISSUE TITLE
Ideas for high-level structure for playbook/toolkit

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/code-gov-open-source-toolkit#2]
It might be helpful to start with a high-level structure to guide the work. Here are some ideas. This is very high-level and incomplete, but perhaps it could serve as a starting point.

## By phase
The phases of getting started with an open source project, along with which team members should be involved in each phase.

### Possible structure
1. Deciding if open source is right for your agency
1. Deciding if open source is right for your product or service
1. Getting buy-in from leadership and stakeholders
1. Choosing open technologies
1. Security and compliance
1. Hosting and building
1. Supporting reusability and sharing
1. Inviting and coordinating contributions
1. Maintenance considerations

## By audience
Organize plays by audience, and tailor the plays to each.

### Possible structure
- CIO
  1. Deciding if open source is right for your agency
  1. Moving to open source from closed
  1. Hiring an open source team
  1. Security and compliance
  1. Maintenance considerations

- Developer
  1. How to choose open source technologies
  1. Migrating to open source
  1. Security and compliance
  1. Maintenance considerations
  1. Communicating about open source

- Product managers
  1. Deciding if open source is right for your product
  1. Organizing your team
  1. Working with open source
  1. Maintenance considerations
  1. Communicating about open source

## By project
Organize plays by product/project.

  1. Deciding if open source is right for your product
  1. Organizing a team
  1. Hosting and building
  1. Security and compliance
  1. Supporting reusability and sharing
  1. Inviting and managing contributions
  1. Maintenance considerations
  1. Communicating about open source

**Comment by Karentrebon** [comment]
I was thinking about sections on 1) procuring in an open source way 2) making sure contractors are working in the open 3) how feds can work in the open 4) how to open source code that was not developed in the open, if that's possible 5) how to inventory code so that it's discoverable on code.gov 6) organizing repos 7) documenting code so that it is re-usable 8) cultivating community. So my thoughts were jumbled between audiences and phases. Mr. Johnson's thoughts are much better organized than mine.

**Comment by jcastle-zz** [comment]
I like this format and going to incorporate pieces of it into the README file. Then build out markdown docs to match.
